language: node_js
arch:
  - amd64
  - ppc64le
dist: trusty
os:
  - linux
  - osx
node_js:
- '6'
- '8'
- 'lts/*'
- 'node'
before_install:
  - npm i -g npm@latest
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libnotify-bin; fi
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
